@echo off
echo Continuing means that any damage caused to your systems registry, or any damage at all, you are resonsible for. Consider this a warning before continuing.
Echo in the case you agree, follow the prompt, else close this window now.
pause
echo creating registry file...
echo Windows Registry Editor Version 5.00>"%userprofile%\regtweak.reg"
echo [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]>>"%userprofile%\regtweak.reg"
echo "HideFileExt"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "ServerAdminUI"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "Hidden"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "Start_SearchFiles"=dword:00000002>>"%userprofile%\regtweak.reg"
echo "HideIcons"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "MapNetDrvBtn"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "WebView"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "Filter"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "ShowSuperHidden"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "SeparateProcess"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "AutoCheckSelect"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "IconsOnly"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "ShowTypeOverlay"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "ShowStatusBar"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "ListviewAlphaSelect"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "ListviewShadow"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "TaskbarAnimations"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "TaskbarSizeMove"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "DisablePreviewDesktop"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "TaskbarSmallIcons"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "TaskbarGlomLevel"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "MMTaskbarGlomLevel"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "TaskbarAutoHideInTabletMode"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "MMTaskbarMode"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "MMTaskbarEnabled"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "ShellMigrationLevel"=dword:00000003>>"%userprofile%\regtweak.reg"
echo "StartMigratedBrowserPin"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "StartShownOnUpgrade"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "ReindexedProfile"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "StartMenuInit"=dword:0000000d>>"%userprofile%\regtweak.reg"
echo "TaskbarMn"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "TaskbarSi"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "Start_ShowClassicMode"=dword:00000000>>"%userprofile%\regtweak.reg"
echo [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control]>>"%userprofile%\regtweak.reg"
echo "WaitToKillServiceTimeout"="5000">>"%userprofile%\regtweak.reg"
echo [HKEY_CURRENT_USER\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32]>>"%userprofile%\regtweak.reg"
echo @="">>"%userprofile%\regtweak.reg"
echo [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization]>>"%userprofile%\regtweak.reg"
echo "NoLockScreen"=dword:00000000>>"%userprofile%\regtweak.reg"
echo [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell\Update\Packages]>>"%userprofile%\regtweak.reg"
echo "UndockingDisabled"=dword:00000000>>"%userprofile%\regtweak.reg"
echo [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Search]>>"%userprofile%\regtweak.reg"
echo "SearchboxTaskbarMode"=dword:00000001>>"%userprofile%\regtweak.reg"
echo [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced]>>"%userprofile%\regtweak.reg"
echo "ShowTaskViewButton"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "ShowCortanaButton"=dword:00000000>>"%userprofile%\regtweak.reg"
echo [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer]>>"%userprofile%\regtweak.reg"
echo "NoTaskGrouping"=dword:00000000>>"%userprofile%\regtweak.reg"
echo [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]>>"%userprofile%\regtweak.reg"
echo "ConsentPromptBehaviorAdmin"=dword:00000002>>"%userprofile%\regtweak.reg"
echo "EnableCursorSuppression"=dword:00000000>>"%userprofile%\regtweak.reg"
echo "EnableInstallerDetection"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "EnableLUA"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "shutdownwithoutlogon"=dword:00000001>>"%userprofile%\regtweak.reg"
echo "verbosestatus"=dword:00000000>>"%userprofile%\regtweak.reg"
echo [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes]>>"%userprofile%\regtweak.reg"
echo "Drop Shadow"="TRUE">>"%userprofile%\regtweak.reg"
echo "Flat Menus"="FALSE">>"%userprofile%\regtweak.reg"
echo "InstallTheme"="C:\\Windows\\resources\\Themes\\areo.theme">>"%userprofile%\regtweak.reg"
echo "InstallThemeDark"="C:\\Windows\\resources\\Themes\\dark.theme">>"%userprofile%\regtweak.reg"
echo "InstallThemeLight"="C:\\Windows\\resources\\Themes\\areo.theme">>"%userprofile%\regtweak.reg"
echo "InstallVisualStyle"="%ResourceDir%\\themes\\Aero\\Aero.msstyles">>"%userprofile%\regtweak.reg"
echo Registry file made...
echo If asked for administrator permissoins, click yes. follow the prompt to continue.
echo If you have changed your mind, and dont want to make these changes, close the window.
pause
echo click yes to continue, no to cancel...
"%userprofile%\regtweak.reg"
echo Please save any work, script is scheduling a restart to apply changes. You can close this window.
shutdown -r -t 120
pause >nul